server:
  port: 7070
jsf:
  STATE_SAVING_METHOD: client
  PROJECT_STAGE: Production
#  bootsfaces:
#    getJqueryFromCdn: true    
  butterfaces:
    provideJQuery: true
    useCompressedResources: true